apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyperf-agent-client-deployment
  namespace: local-ai-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyperf-agent
  template:
    metadata:
      labels:
        app: cyperf-agent
    spec:
      containers:
        - name: cyperf-agent-client
          image: public.ecr.aws/keysight/cyperf-agent:release6.0_debug
          env:
          - name: AGENT_CONTROLLER
            value: sec-cyperf.departmentofdemos.com
          # name: AGENT_MANAGEMENT_INTERFACE
          # value: "eth0"
          # name: AGENT_TEST_INTERFACE
          # value: "eth1"
          - name: AGENT_TAGS
            value: "K8s-Group=CyPerf-Agent-Client,user=Client"
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_ADMIN", "IPC_LOCK", "NET_RAW"]
          resources:
            limits:
              memory: "4Gi"
              #cpu: "3.5"
              ## skipping requests means limits=requests
              ## with 3.5 for 8 core node it should be able to run 2 replicas
              ## but experiments needed to see how other pods react for perf configs.
            requests:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /etc/systemd/timesyncd.conf
              name: timesyncd
            - mountPath: /etc/localtime
              subPath: America/New_York
              name: timezone
      volumes:
        - name: timesyncd
          hostPath:
            path: /etc/systemd/timesyncd.conf
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo
#      nodeSelector:
#        agenttype: client
