apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-claim
  name: n8n-claim
  namespace: local-ai-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
