apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: local-ai-lab
spec:
  serviceName: "ollama"
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["/bin/sh"]
        ports:
        - containerPort: 11434
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "4Gi"
            nvidia.com/gpu: "0"
        volumeMounts:
        - name: ollama-volume
          mountPath: /root/.ollama
        tty: true
  volumeClaimTemplates:
  - metadata:
      name: ollama-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi


---
apiVersion: v1
kind: Pod
metadata:
  name: init-ollama
  namespace: local-ai-lab
  labels:
    purpose: init-command
spec:
  containers:
  - name: ollama-pull-llama
    image: ollama/ollama:latest
    command: ["/bin/sh"]
    args: ["-c","sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.2; OLLAMA_HOST=ollama:11434 ollama pull llama3.2-vision:11b"]
    volumeMounts:
    - name: ollama-volume
      mountPath: /root/.ollama
  restartPolicy: OnFailure
